spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

code:
  gen:
    masterUrl: jdbc:mysql://localhost:3306/code-gen?serverTimezone=UTC
    masterUserName: root
    masterPassword: root
    slaveUrl: jdbc:mysql://localhost:3306/lipop?serverTimezone=UTC
    slaveUserName: root
    slavePassword: root
